In [7]:
from custom_envs.dm_control_suite import get_default_config, load, get_domain_randomizer
from custom_envs.manipulation import get_default_config, load, get_domain_randomizer
import jax
import jax.numpy as jnp
import os
from learning.module.wrapper.adv_wrapper import wrap_for_adv_training
from learning.module.wrapper.dr_wrapper import wrap_for_dr_training
import functools
# os.environ["CUDA_VISIBLE_DEVICES"] = "5"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"]='false'


In [10]:
env_name='LeapCubeRotateZAxis'
cfg = get_default_config(env_name)
env = load(env_name, cfg)
# randomizer = get_domain_randomizer(env_name)
# randomizer = functools.partial(randomizer, dr_range=env.dr_range)

# eval_env = wrap_for_adv_training(
#       env,
#       episode_length=1000,
#       action_repeat=2,
#       randomization_fn=randomizer,
# )
# eval_env2 = wrap_for_dr_training(
#       env,
#       episode_length=1000,
#       action_repeat=2,
#       randomization_fn=randomizer,
#       n_envs=1,
#       n_nominals=1,
# )


W1230 17:28:04.481960 2963103 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.
W1230 17:28:04.486217 2962652 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.


In [ ]:
evaluator = AdvEvaluator(
        eval_env,
        lambda x : x,
        num_eval_envs=128,
        episode_length=1000,
        action_repeat=2,
        key=jax.random.PRNGKey(0),
    )


NameError: name 'AdvEvaluator' is not defined

In [ ]:
dynamics_params = jnp.zeros((128,14))
metrics = evaluator.run_evaluation(dynamics_params, dynamics_params, {})


In [3]:
env.mjx_model.body_ipos


Array([[ 0.        ,  0.        ,  0.        ],
       [-0.00386404,  0.        , -0.04636852],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-0.02      ,  0.        ,  0.        ],
       [ 0.        ,  0.005     , -0.17      ],
       [ 0.        ,  0.        , -0.15      ],
       [ 0.035     , -0.01      ,  0.        ],
       [ 0.        , -0.005     , -0.17      ],
       [ 0.        ,  0.        , -0.15      ],
       [ 0.035     ,  0.01      ,  0.        ],
       [ 0.08      , -0.08      , -0.08      ],
       [ 0.09      ,  0.09      ,  0.09      ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.08      ,  0.08      , -0.08      ],
       [ 0.09      , -0.09      ,  0.09      ],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32)

In [ ]:
state.data.geom_xpos


In [11]:
env.mjx_model.geom_friction


Array([[1.e+00, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [7.e-01, 5.e-02, 2.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.e-01, 5.e-03, 1.e-04],
       [2.

In [13]:
env.mjx_model.dof_frictionloss.shape


(27,)

In [13]:
env.mjx_model.nv


22

In [16]:
env.mjx_model.nu


16

In [14]:
env.mjx_model.qpos0.shape


(23,)

In [4]:
from mujoco import mj_id2name, mj_name2id
import mujoco
[mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(env.mj_model.nbody)]


['world',
 'torso',
 'head',
 'lower_waist',
 'pelvis',
 'right_thigh',
 'right_shin',
 'right_foot',
 'left_thigh',
 'left_shin',
 'left_foot',
 'right_upper_arm',
 'right_lower_arm',
 'right_hand',
 'left_upper_arm',
 'left_lower_arm',
 'left_hand']

In [5]:
[mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_JOINT, i) for i in range(env.mj_model.njnt)]



['root',
 'abdomen_z',
 'abdomen_y',
 'abdomen_x',
 'right_hip_x',
 'right_hip_z',
 'right_hip_y',
 'right_knee',
 'right_ankle_y',
 'right_ankle_x',
 'left_hip_x',
 'left_hip_z',
 'left_hip_y',
 'left_knee',
 'left_ankle_y',
 'left_ankle_x',
 'right_shoulder1',
 'right_shoulder2',
 'right_elbow',
 'left_shoulder1',
 'left_shoulder2',
 'left_elbow']

In [ ]:
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_GEOM, i), 
        env.mj_model.geom_friction[i]
    ) 
    for i in range(env.mj_model.ngeom)
]


[('floor', array([0.7, 0.1, 0.1])),
 ('torso', array([0.7, 0.1, 0.1])),
 ('right_thigh', array([0.7, 0.1, 0.1])),
 ('right_leg', array([0.7, 0.1, 0.1])),
 ('right_foot', array([0.7, 0.1, 0.1])),
 ('left_thigh', array([0.7, 0.1, 0.1])),
 ('left_leg', array([0.7, 0.1, 0.1])),
 ('left_foot', array([0.7, 0.1, 0.1]))]

In [ ]:
env.mj_model.body_ipos
e


Array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-1.0937017e-03,  0.0000000e+00,  1.2999601e+00],
       [ 1.5179434e-02, -5.0000001e-02,  1.5995185e+00],
       [-6.7216510e-01, -5.0000001e-02,  1.7078959e+00],
       [-9.4144118e-01, -5.0000001e-02,  1.7309064e+00],
       [ 1.5179434e-02,  5.0000001e-02,  1.5995185e+00],
       [ 1.7223194e-01,  5.0000001e-02,  2.2128611e+00],
       [ 3.1954986e-01,  5.0000001e-02,  2.4210989e+00]], dtype=float32)

In [ ]:
env.dt


0.025

In [ ]:
init_state=  env.reset(jax.random.PRNGKey(0))
state=init_state


In [ ]:
state = env.step(state, jnp.ones(env.action_size))
state.data.xpos


Array([[ 0.        ,  0.        ,  0.        ],
       [-0.00273224,  0.        ,  1.2999129 ],
       [ 0.01732769, -0.05      ,  1.5992415 ],
       [-0.6702935 , -0.05      ,  1.706525  ],
       [-0.93839103, -0.05      ,  1.727882  ],
       [ 0.01732769,  0.05      ,  1.5992415 ],
       [ 0.17167605,  0.05      ,  2.21286   ],
       [ 0.31705746,  0.05      ,  2.4200392 ]], dtype=float32)

In [ ]:
import jax.numpy as jnp
a = jnp.arange(10)


W1230 14:55:07.471246 2904513 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.
W1230 14:55:07.475094 2903935 cuda_executor.cc:1802] GPU interconnect information not available: INTERNAL: NVML doesn't support extracting fabric info or NVLink is not used by the device.


In [ ]:
a[2:10:3]


Array([2, 5, 8], dtype=int32)