In [1]:
from custom_envs.dm_control_suite import get_default_config, load, get_domain_randomizer
from custom_envs.manipulation import get_default_config, load, get_domain_randomizer
import jax
import jax.numpy as jnp
import os
from learning.module.wrapper.adv_wrapper import wrap_for_adv_training
from learning.module.wrapper.dr_wrapper import wrap_for_dr_training
import functools
# os.environ["CUDA_VISIBLE_DEVICES"] = "5"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"]='false'
import mediapy as media


Warp DeprecationWarning: The namespace `warp.context` will soon be removed from the public API. It can still be accessed from `warp._src.context` but might be changed or removed without notice.
Warp DeprecationWarning: The symbol `warp.context.Module` will soon be removed from the public API. Use `warp.Module` instead.
Warp DeprecationWarning: The symbol `warp.context.get_module` will soon be removed from the public API. Use `warp.get_module` instead.
Warp DeprecationWarning: The namespace `warp.math` will soon be removed from the public API. It can still be accessed from `warp._src.math` but might be changed or removed without notice.


In [ ]:
env_name='AlohaSingl'
cfg = get_default_config(env_name)
env = load(env_name, cfg)


In [35]:
jit_step = jax.jit(env.step)
jit_reset = jax.jit(env.reset)


In [36]:
init_state = jit_reset(jax.random.PRNGKey(2))
state = init_state


In [37]:
seconds = 3
rollout=[state]
for i in range(int(seconds/env.sim_dt)):
    state = jit_step(state, jnp.ones(env.action_size))
    rollout.append(state)
frames = env.render(rollout, camera="fixed")
media.show_video(frames, fps=1.0 / env.sim_dt)


/home/sukchul/miniconda3/envs/jax_flow/lib/python3.12/site-packages/jax/_src/abstract_arrays.py:135: RuntimeWarning: overflow encountered in cast
  return literals.TypedNdArray(np.asarray(x, dtype), weak_type=False)
/home/sukchul/miniconda3/envs/jax_flow/lib/python3.12/site-packages/jax/_src/abstract_arrays.py:135: RuntimeWarning: overflow encountered in cast
  return literals.TypedNdArray(np.asarray(x, dtype), weak_type=False)
  0%|          | 0/601 [00:00<?, ?it/s]


ValueError: The camera "fixed" does not exist.

In [39]:
frames = env.render(rollout)
media.show_video(frames, fps=1.0 / env.sim_dt)


100%|██████████| 601/601 [00:02<00:00, 228.91it/s]


In [6]:
import mujoco
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i), 
        state.data.xpos[i]
    ) 
    for i in range(env.mj_model.nbody)
]


[('world', Array([0., 0., 0.], dtype=float32)),
 ('left/base_link', Array([-0.469, -0.019,  0.02 ], dtype=float32)),
 ('left/shoulder_link',
  Array([-0.469     , -0.019     ,  0.09900001], dtype=float32)),
 ('left/upper_arm_link',
  Array([-0.469     , -0.019     ,  0.14705001], dtype=float32)),
 ('left/upper_forearm_link',
  Array([-0.7722683 , -0.01934412,  0.18672943], dtype=float32)),
 ('left/lower_forearm_link',
  Array([-0.5805838 , -0.01912662,  0.12965919], dtype=float32)),
 ('left/wrist_link',
  Array([-0.48474157, -0.01901786,  0.10112408], dtype=float32)),
 ('left/gripper_link',
  Array([-0.5304208 , -0.07002757,  0.08787084], dtype=float32)),
 ('left/gripper_base',
  Array([-0.5533442 , -0.09562605,  0.0812199 ], dtype=float32)),
 ('left/left_finger_link',
  Array([-0.590278  , -0.07938785,  0.03465889], dtype=float32)),
 ('left/right_finger_link',
  Array([-0.56459594, -0.12776738,  0.13234785], dtype=float32)),
 ('right/base_link', Array([ 0.469, -0.019,  0.02 ], dtype=f

In [7]:
env.mjx_model.opt.gravity


Array([ 0.  ,  0.  , -9.81], dtype=float32)

In [8]:
env.mjx_model.body_ipos


Array([[ 0.00000e+00,  0.00000e+00,  0.00000e+00],
       [-5.34774e-02, -5.62575e-04,  2.05961e-02],
       [ 2.59233e-04, -3.35520e-06,  1.16129e-02],
       [ 2.06949e-02,  4.00000e-10,  2.26459e-01],
       [ 1.05723e-01,  0.00000e+00,  0.00000e+00],
       [ 5.13477e-02,  6.80462e-03,  0.00000e+00],
       [ 4.67430e-02, -7.66520e-06,  1.05650e-02],
       [ 3.95662e-02, -2.56311e-07,  4.00649e-03],
       [ 1.82154e-04, -3.41589e-02, -1.06026e-02],
       [ 1.43478e-02, -2.84791e-02,  1.22897e-02],
       [ 1.43711e-02,  2.84792e-02,  1.21421e-02],
       [-5.34774e-02, -5.62575e-04,  2.05961e-02],
       [ 2.59233e-04, -3.35520e-06,  1.16129e-02],
       [ 2.06949e-02,  4.00000e-10,  2.26459e-01],
       [ 1.05723e-01,  0.00000e+00,  0.00000e+00],
       [ 5.13477e-02,  6.80462e-03,  0.00000e+00],
       [ 4.67430e-02, -7.66520e-06,  1.05650e-02],
       [ 3.95662e-02, -2.56311e-07,  4.00649e-03],
       [ 1.82154e-04, -3.41589e-02, -1.06026e-02],
       [ 1.43478e-02, -2.84791e

In [9]:
state.data.geom_xpos


Array([[ 0.00000000e+00,  0.00000000e+00, -7.50000000e-01],
       [ 2.21624432e-04,  2.00238924e-06, -7.19125569e-03],
       [ 2.29881902e-04, -3.50209906e-09, -3.81125212e-01],
       [ 0.00000000e+00,  0.00000000e+00,  7.99999980e-04],
       [ 2.38418441e-09, -3.61000001e-01,  1.02999997e+00],
       [ 5.14999986e-01, -3.70999992e-01,  6.10000014e-01],
       [-5.83634428e-05, -3.08492273e-01,  1.03533196e+00],
       [ 4.15492356e-01, -3.82992119e-01,  1.01549232e+00],
       [ 1.43051126e-08, -3.91000003e-01, -9.99999978e-03],
       [-5.14999986e-01, -3.70999992e-01,  6.10000014e-01],
       [ 4.44507629e-01, -3.82992119e-01,  5.95492363e-01],
       [-5.83634428e-05, -3.88248384e-01,  3.05454843e-02],
       [ 5.85492373e-01, -3.82992119e-01,  5.95492363e-01],
       [-4.30000007e-01, -3.61000001e-01,  5.19999981e-01],
       [-5.85492373e-01, -3.82992119e-01,  5.95492363e-01],
       [-4.30000007e-01, -2.39706829e-01,  1.20292827e-01],
       [-5.14999986e-01, -6.59999996e-02

In [10]:
env.mjx_model.geom_friction


Array([[1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.

In [11]:
env.mjx_model.dof_frictionloss


Array([0.  , 2.  , 1.15, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 2.  , 1.15,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],      dtype=float32)

In [12]:
env.mjx_model.dof_armature


Array([0.   , 0.395, 0.383, 0.14 , 0.008, 0.   , 0.243, 0.243, 0.   ,
       0.395, 0.383, 0.14 , 0.008, 0.   , 0.243, 0.243, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   ], dtype=float32)

In [13]:
env.mjx_model.dof_damping


Array([ 5.76, 20.  , 18.49,  6.78,  6.28,  1.2 , 40.  , 40.  ,  5.76,
       20.  , 18.49,  6.78,  6.28,  1.2 , 40.  , 40.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ], dtype=float32)

In [14]:
env.mjx_model.nv


22

In [15]:
env.mjx_model.nu


14

In [16]:
env.mjx_model.qpos0.shape


(23,)

In [17]:
env.mjx_model.actuator_gainprm


Array([[ 43. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [265. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [227. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [ 78. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [ 37. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [ 10.4,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [365. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [ 43. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [265. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [227. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [ 78. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [ 37. ,   0. ,   0. ,   0. ,   0. , 

In [18]:
env.mjx_model.actuator_biasprm


Array([[   0. ,  -43. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. , -265. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. , -227. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. ,  -78. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. ,  -37. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. ,  -10.4,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. , -365. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. ,  -43. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. , -265. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. , -227. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
           0. ,    0. ],
       [   0. ,  -78. ,    0. 

In [19]:
from mujoco import mj_id2name, mj_name2id
import mujoco
[mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(env.mj_model.nbody)]


['world',
 'left/base_link',
 'left/shoulder_link',
 'left/upper_arm_link',
 'left/upper_forearm_link',
 'left/lower_forearm_link',
 'left/wrist_link',
 'left/gripper_link',
 'left/gripper_base',
 'left/left_finger_link',
 'left/right_finger_link',
 'right/base_link',
 'right/shoulder_link',
 'right/upper_arm_link',
 'right/upper_forearm_link',
 'right/lower_forearm_link',
 'right/wrist_link',
 'right/gripper_link',
 'right/gripper_base',
 'right/left_finger_link',
 'right/right_finger_link',
 'box',
 'mocap_target']

In [20]:

[
    (
        mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_JOINT, i),
        env.mj_model.dof_frictionloss[i]
    )
    for i in range(env.mj_model.njnt)]


[('left/waist', np.float64(0.0)),
 ('left/shoulder', np.float64(2.0)),
 ('left/elbow', np.float64(1.15)),
 ('left/forearm_roll', np.float64(0.0)),
 ('left/wrist_angle', np.float64(0.0)),
 ('left/wrist_rotate', np.float64(0.0)),
 ('left/left_finger', np.float64(0.0)),
 ('left/right_finger', np.float64(0.0)),
 ('right/waist', np.float64(0.0)),
 ('right/shoulder', np.float64(2.0)),
 ('right/elbow', np.float64(1.15)),
 ('right/forearm_roll', np.float64(0.0)),
 ('right/wrist_angle', np.float64(0.0)),
 ('right/wrist_rotate', np.float64(0.0)),
 ('right/left_finger', np.float64(0.0)),
 ('right/right_finger', np.float64(0.0)),
 (None, np.float64(0.0))]

In [21]:
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_GEOM, i), 
        env.mj_model.geom_friction[i]
    ) 
    for i in range(env.mj_model.ngeom)
]


[('floor', array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 ('table', array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-0

In [22]:
env.mj_model.geom_friction.shape



(97, 3)

In [23]:
env._left_finger_geom


AttributeError: 'HandOver' object has no attribute '_left_finger_geom'

In [ ]:
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i), 
        env.mj_model.body_mass[i]
    ) 
    for i in range(env.mj_model.nbody)
]


[('world', np.float64(0.0)),
 ('link0', np.float64(0.629769)),
 ('link1', np.float64(4.970684)),
 ('link2', np.float64(0.646926)),
 ('link3', np.float64(3.228604)),
 ('link4', np.float64(3.587895)),
 ('link5', np.float64(1.225946)),
 ('link6', np.float64(1.666555)),
 ('link7', np.float64(0.735522)),
 ('panda_robotiq_fts300', np.float64(0.0)),
 ('base_mount', np.float64(0.06582648376132798)),
 ('fts300_body', np.float64(0.3)),
 ('fts300_sensor_body', np.float64(0.08684233046785128)),
 ('base', np.float64(0.777441)),
 ('left_driver', np.float64(0.00899563)),
 ('left_coupler', np.float64(0.0140974)),
 ('left_spring_link', np.float64(0.0221642)),
 ('left_follower', np.float64(0.0125222)),
 ('left_pad', np.float64(1e-06)),
 ('right_driver', np.float64(0.00899563)),
 ('right_coupler', np.float64(0.0140974)),
 ('right_spring_link', np.float64(0.0221642)),
 ('right_follower', np.float64(0.0125222)),
 ('right_pad', np.float64(1e-06)),
 ('box', np.float64(0.15)),
 ('mocap_target', np.float64(3.5

In [ ]:

init_state=  env.reset(jax.random.PRNGKey(0))
state=init_state



In [ ]:
from custom_envs import mjx_env


state.data
mjx_env.get_sensor_data(
        env.mj_model, state.data, "torso_subtreelinvel"
    )


KeyError: "Invalid name 'torso_subtreelinvel'. Valid names: ['floor_hand_capsule_found', 'floor_left_finger_pad_found', 'floor_right_finger_pad_found', 'left_coupler_col_1_box_normal', 'left_coupler_col_2_box_normal', 'left_follower_pad2_box_normal', 'right_coupler_col_1_box_normal', 'right_coupler_col_2_box_normal', 'right_follower_pad2_box_normal', 'wall_hand_capsule_found', 'wall_left_finger_pad_found', 'wall_right_finger_pad_found']"

In [ ]:
state = env.step(state, jnp.ones(env.action_size))
state.data.xpos



In [ ]:
from learning.module.wrapper.evaluator import AdvEvaluator


evaluator = AdvEvaluator(
        env,
        lambda x : x,
        num_eval_envs=128,
        episode_length=1000,
        action_repeat=2,
        key=jax.random.PRNGKey(0),
    )
dynamics_params = jnp.zeros((128,14))
metrics = evaluator.run_evaluation(dynamics_params, dynamics_params, {})
