In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "3"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"]='false'
from custom_envs.dm_control_suite import get_default_config, load, get_domain_randomizer
from custom_envs.manipulation import get_default_config, load, get_domain_randomizer

from learning.module.wrapper.adv_wrapper import wrap_for_adv_training
from learning.module.wrapper.dr_wrapper import wrap_for_dr_training
import functools

import jax
import jax.numpy as jnp
import mediapy as media


In [2]:
env_name='PandaNutThread'
cfg = get_default_config(env_name)
env = load(env_name, cfg)


In [3]:
jit_step = jax.jit(env.step)
jit_reset = jax.jit(env.reset)


In [4]:
init_state = jit_reset(jax.random.PRNGKey(2))
state = init_state


In [5]:
seconds = 3
rollout=[state]
for i in range(int(seconds/env.sim_dt)):
    state = jit_step(state, jnp.ones(env.action_size))
    rollout.append(state)
frames = env.render(rollout)
media.show_video(frames, fps=1.0 / env.sim_dt)


/home/tjrcjf410/miniconda3/envs/mujoco2/lib/python3.11/site-packages/jax/_src/abstract_arrays.py:135: RuntimeWarning: overflow encountered in cast
  return literals.TypedNdArray(np.asarray(x, dtype), weak_type=False)
/home/tjrcjf410/miniconda3/envs/mujoco2/lib/python3.11/site-packages/glfw/__init__.py:917: GLFWError: (65550) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
/home/tjrcjf410/miniconda3/envs/mujoco2/lib/python3.11/site-packages/glfw/__init__.py:917: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
100%|██████████| 601/601 [00:02<00:00, 231.24it/s]


In [6]:
frames = env.render(rollout)
media.show_video(frames, fps=1.0 / env.sim_dt)


100%|██████████| 601/601 [00:02<00:00, 260.40it/s]


In [7]:
import mujoco
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i), 
        state.data.xpos[i]
    ) 
    for i in range(env.mj_model.nbody)
]


[('world', Array([0., 0., 0.], dtype=float32)),
 ('link0', Array([0., 0., 0.], dtype=float32)),
 ('link1', Array([0.   , 0.   , 0.333], dtype=float32)),
 ('link2', Array([0.   , 0.   , 0.333], dtype=float32)),
 ('link3', Array([-0.29886657,  0.08398948,  0.27400398], dtype=float32)),
 ('link4', Array([-0.31890443,  0.06772904,  0.35236424], dtype=float32)),
 ('link5', Array([-0.6742813 ,  0.18153408,  0.22981675], dtype=float32)),
 ('link6', Array([-0.6742813 ,  0.18153408,  0.22981675], dtype=float32)),
 ('link7', Array([-0.6109303 ,  0.19662791,  0.170632  ], dtype=float32)),
 ('hand', Array([-0.6826128 ,  0.24211322,  0.10550364], dtype=float32)),
 ('left_finger',
  Array([-0.73873746,  0.27656427,  0.09539097], dtype=float32)),
 ('right_finger',
  Array([-0.704857  ,  0.25738198,  0.04470413], dtype=float32)),
 ('nut', Array([0.52001566, 0.14002644, 0.02269172], dtype=float32)),
 ('peg', Array([ 0.63956827, -0.11895483,  0.        ], dtype=float32)),
 ('mocap_target',
  Array([ 0.6

In [8]:
env.mjx_model.opt.gravity


Array([ 0.  ,  0.  , -9.81], dtype=float32)

In [9]:
env.mjx_model.body_ipos


Array([[ 0.        ,  0.        ,  0.        ],
       [-0.041018  , -0.00014   ,  0.049974  ],
       [ 0.003875  ,  0.002081  , -0.04762   ],
       [-0.003141  , -0.02872   ,  0.003495  ],
       [ 0.027518  ,  0.039252  , -0.066502  ],
       [-0.05317   ,  0.104419  ,  0.027454  ],
       [-0.011953  ,  0.041065  , -0.038437  ],
       [ 0.060149  , -0.014117  , -0.010517  ],
       [ 0.010517  , -0.004252  ,  0.061597  ],
       [-0.01      ,  0.        ,  0.03      ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.01568317,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.04781001],
       [ 0.        ,  0.        ,  0.114     ]], dtype=float32)

In [10]:
state.data.geom_xpos


Array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-2.4341708e-02,  6.8985842e-02,  3.7001297e-02],
       [-2.5005136e-02,  7.2889678e-02,  3.6978751e-02],
       [-2.3746833e-02, -6.5352961e-02,  6.2999323e-02],
       [-2.4884207e-02, -7.2681338e-02,  6.2931284e-02],
       [-6.4821176e-02, -6.5604247e-02,  4.8001379e-02],
       [-5.9638858e-02,  5.7885069e-02,  3.6908485e-02],
       [ 1.1052804e-02, -7.2000034e-02,  4.6062700e-02],
       [-2.9952925e-02, -3.4480123e-05,  5.3494547e-02],
       [-2.4999274e-02, -7.3032074e-02,  3.2895043e-02],
       [-2.3787200e-02, -6.5486304e-02,  3.2974105e-02],
       [ 1.1042832e-02,  7.1996957e-02,  4.6087444e-02],
       [-2.9189765e-02, -8.7946572e-04,  5.6603190e-02],
       [ 8.7850215e-03,  3.1268738e-02,  2.6542413e-01],
       [ 8.4478008e-03,  3.0102625e-02,  2.6362669e-01],
       [-7.3596805e-02, -1.2774793e-02,  3.2018909e-01],
       [-7.4946269e-02, -1.1324115e-02,  3.1988418e-01],
       [-2.6845542e-01,  8.8939

In [11]:
env.mjx_model.geom_friction


Array([[1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.

In [12]:
env.mjx_model.dof_frictionloss


Array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],      dtype=float32)

In [13]:
env.mjx_model.dof_armature


Array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. ], dtype=float32)

In [14]:
env.mjx_model.dof_damping


Array([4.e+01, 4.e+01, 4.e+01, 4.e+01, 2.e+00, 2.e+00, 2.e+00, 1.e+01,
       1.e+01, 1.e-02, 1.e-02, 1.e-02, 1.e-02, 1.e-02, 1.e-02, 0.e+00,
       0.e+00], dtype=float32)

In [15]:
env.mjx_model.nv


17

In [16]:
env.mjx_model.nu


8

In [17]:
env.mjx_model.qpos0.shape


(18,)

In [18]:
env.mjx_model.actuator_gainprm


Array([[1000.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [1000.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [ 750.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [ 750.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [ 300.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [ 300.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [ 300.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [ 350.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.]], dtype=float32)

In [19]:
env.mjx_model.actuator_biasprm


Array([[    0., -1000.,   -20.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0., -1000.,   -20.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,  -750.,    -4.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,  -750.,    -4.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,  -300.,    -2.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,  -300.,    -2.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,  -300.,    -2.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.],
       [    0.,  -350.,   -10.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.]], dtype=float32)

In [20]:
from mujoco import mj_id2name, mj_name2id
import mujoco
[mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(env.mj_model.nbody)]


['world',
 'link0',
 'link1',
 'link2',
 'link3',
 'link4',
 'link5',
 'link6',
 'link7',
 'hand',
 'left_finger',
 'right_finger',
 'nut',
 'peg',
 'mocap_target']

In [21]:

[
    (
        mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_JOINT, i),
        env.mj_model.dof_frictionloss[i]
    )
    for i in range(env.mj_model.njnt)]


[('joint1', np.float64(0.0)),
 ('joint2', np.float64(0.0)),
 ('joint3', np.float64(0.0)),
 ('joint4', np.float64(0.0)),
 ('joint5', np.float64(0.0)),
 ('joint6', np.float64(0.0)),
 ('joint7', np.float64(0.0)),
 ('finger_joint1', np.float64(0.0)),
 ('finger_joint2', np.float64(0.0)),
 (None, np.float64(0.0)),
 ('peg_x', np.float64(0.0)),
 ('peg_y', np.float64(0.0))]

In [22]:
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_GEOM, i), 
        env.mj_model.geom_friction[i]
    ) 
    for i in range(env.mj_model.ngeom)
]


[('floor', array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 1.e-04])),
 (None, array([1.e+00, 5.e-03, 

In [23]:
env.mj_model.geom_friction.shape



(89, 3)

In [24]:
env._left_finger_geom


73

In [25]:
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i), 
        env.mj_model.body_mass[i]
    ) 
    for i in range(env.mj_model.nbody)
]


[('world', np.float64(0.0)),
 ('link0', np.float64(0.629769)),
 ('link1', np.float64(4.970684)),
 ('link2', np.float64(0.646926)),
 ('link3', np.float64(3.228604)),
 ('link4', np.float64(3.587895)),
 ('link5', np.float64(1.225946)),
 ('link6', np.float64(1.666555)),
 ('link7', np.float64(0.735522)),
 ('hand', np.float64(0.73)),
 ('left_finger', np.float64(0.015)),
 ('right_finger', np.float64(0.015)),
 ('nut', np.float64(0.959904)),
 ('peg', np.float64(1.6917119999999999)),
 ('mocap_target', np.float64(1.387152))]

In [26]:

init_state=  env.reset(jax.random.PRNGKey(0))
state=init_state



In [ ]:
from custom_envs import mjx_env


state.data
mjx_env.get_sensor_data(
        env.mj_model, state.data, "torso_subtreelinvel"
    )


KeyError: "Invalid name 'torso_subtreelinvel'. Valid names: ['hand_capsule_floor_found', 'left_finger_pad_floor_found', 'nut_handle_hand_found', 'right_finger_pad_floor_found']"

: 

In [ ]:
state = env.step(state, jnp.ones(env.action_size))
state.data.xpos



In [ ]:
from learning.module.wrapper.evaluator import AdvEvaluator


evaluator = AdvEvaluator(
        env,
        lambda x : x,
        num_eval_envs=128,
        episode_length=1000,
        action_repeat=2,
        key=jax.random.PRNGKey(0),
    )
dynamics_params = jnp.zeros((128,14))
metrics = evaluator.run_evaluation(dynamics_params, dynamics_params, {})
