In [1]:
import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "3"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"]='false'
from custom_envs.dm_control_suite import get_default_config, load, get_domain_randomizer
# from custom_envs.manipulation import get_default_config, load, get_domain_randomizer

from learning.module.wrapper.adv_wrapper import wrap_for_adv_training
from learning.module.wrapper.dr_wrapper import wrap_for_dr_training
import functools

import jax
import jax.numpy as jnp
import mediapy as media


Warp DeprecationWarning: The namespace `warp.context` will soon be removed from the public API. It can still be accessed from `warp._src.context` but might be changed or removed without notice.
Warp DeprecationWarning: The symbol `warp.context.Module` will soon be removed from the public API. Use `warp.Module` instead.
Warp DeprecationWarning: The symbol `warp.context.get_module` will soon be removed from the public API. Use `warp.get_module` instead.
Warp DeprecationWarning: The namespace `warp.math` will soon be removed from the public API. It can still be accessed from `warp._src.math` but might be changed or removed without notice.


In [2]:
env_name='AcrobotSwingup'
cfg = get_default_config(env_name)
env = load(env_name, cfg)


Warp 1.11.1 initialized:
   CUDA Toolkit 12.9, Driver 13.0
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 3090" (24 GiB, sm_86, mempool enabled)
   Kernel cache:
     /home/sukchul/.cache/warp/1.11.1
Warp DeprecationWarning: The symbol `warp.context.runtime` will soon be removed from the public API. It can still be accessed from `warp._src.context.runtime` but might be changed or removed without notice.
Warp DeprecationWarning: The symbol `warp.types.warp_type_to_np_dtype` will soon be removed from the public API. It can still be accessed from `warp._src.types.warp_type_to_np_dtype` but might be changed or removed without notice.
Warp DeprecationWarning: The symbol `warp.types.array` will soon be removed from the public API. Use `warp.array` instead.


In [3]:
upper_arm_body_id = env._mj_model.body("upper_arm").id
lower_arm_body_id = env._mj_model.body("lower_arm").id


In [4]:
lower_arm_body_id


2

In [5]:
jit_step = jax.jit(env.step)
jit_reset = jax.jit(env.reset)


In [6]:
init_state = jit_reset(jax.random.PRNGKey(2))
state = init_state


Module mujoco.mjx.third_party.mujoco_warp._src.smooth 03158d3 load on device 'cuda:0' took 7.40 ms  (cached)
Module mujoco.mjx.third_party.mujoco_warp._src.collision_driver de6dc98 load on device 'cuda:0' took 0.36 ms  (cached)
Module mujoco.mjx.third_party.mujoco_warp._src.constraint 1d9ddab load on device 'cuda:0' took 2.07 ms  (cached)
Module _actuator_velocity__locals__actuator_velocity_8cc979e3 7d8b67d load on device 'cuda:0' took 568.06 ms  (compiled)
Module mujoco.mjx.third_party.mujoco_warp._src.passive f9d0821 load on device 'cuda:0' took 2.50 ms  (cached)
Module mujoco.mjx.third_party.mujoco_warp._src.forward 3875c24 load on device 'cuda:0' took 2.79 ms  (cached)
Module mujoco.mjx.third_party.mujoco_warp._src.support b7a7a89 load on device 'cuda:0' took 1.04 ms  (cached)
Module _tile_cholesky_factorize_solve__locals__cholesky_factorize_solve_a2d70a56 a920ae0 load on device 'cuda:0' took 3583.53 ms  (compiled)
Module mujoco.mjx.third_party.mujoco_warp._src.solver f8d7d7e load 

In [7]:
seconds = 3
rollout=[state]
for i in range(int(seconds/env.sim_dt)):
    state = jit_step(state, jnp.ones(env.action_size))
    rollout.append(state)
frames = env.render(rollout)
media.show_video(frames, fps=1.0 / env.sim_dt)


100%|██████████| 301/301 [00:00<00:00, 316.88it/s]


In [8]:
frames = env.render(rollout)
media.show_video(frames, fps=1.0 / env.sim_dt)


100%|██████████| 301/301 [00:00<00:00, 401.17it/s]


In [9]:
import mujoco
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i), 
        state.data.xpos[i]
    ) 
    for i in range(env.mj_model.nbody)
]


[('world', Array([0., 0., 0.], dtype=float32)),
 ('upper_arm', Array([0., 0., 2.], dtype=float32)),
 ('lower_arm', Array([0.16311759, 0.        , 1.0133934 ], dtype=float32))]

In [10]:
env.mjx_model.opt.gravity


Array([ 0.  ,  0.  , -9.81], dtype=float32)

In [11]:
env.mjx_model.body_ipos


Array([[0. , 0. , 0. ],
       [0. , 0. , 0.5],
       [0. , 0. , 0.5]], dtype=float32)

In [12]:
state.data.geom_xpos


Array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.        ],
       [ 0.08155879,  0.        ,  1.5066967 ],
       [-0.11002415,  0.        ,  0.59459317]], dtype=float32)

In [13]:
env.mjx_model.geom_friction


Array([[1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04],
       [1.e+00, 5.e-03, 1.e-04]], dtype=float32)

In [14]:
env.mjx_model.dof_frictionloss


Array([0., 0.], dtype=float32)

In [15]:
env.mjx_model.dof_armature


Array([0., 0.], dtype=float32)

In [16]:
env.mjx_model.dof_damping


Array([0.05, 0.05], dtype=float32)

In [17]:
env.mjx_model.nv


2

In [18]:
env.mjx_model.nu


1

In [19]:
env.mjx_model.qpos0.shape


(2,)

In [20]:
env.mjx_model.actuator_gainprm


Array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [21]:
env.mjx_model.actuator_biasprm


Array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [22]:
from mujoco import mj_id2name, mj_name2id
import mujoco
[mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(env.mj_model.nbody)]


['world', 'upper_arm', 'lower_arm']

In [23]:

[
    (
        mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_JOINT, i),
        env.mj_model.dof_frictionloss[i]
    )
    for i in range(env.mj_model.njnt)]


[('shoulder', np.float64(0.0)), ('elbow', np.float64(0.0))]

In [24]:
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_GEOM, i), 
        env.mj_model.geom_friction[i]
    ) 
    for i in range(env.mj_model.ngeom)
]


[('floor', array([1.e+00, 5.e-03, 1.e-04])),
 ('upper_arm_decoration', array([1.e+00, 5.e-03, 1.e-04])),
 ('upper_arm', array([1.e+00, 5.e-03, 1.e-04])),
 ('lower_arm', array([1.e+00, 5.e-03, 1.e-04]))]

In [25]:
env.mj_model.geom_friction.shape



(4, 3)

In [26]:
env._left_finger_geom


AttributeError: 'Balance' object has no attribute '_left_finger_geom'

In [ ]:
[
    (
        mujoco.mj_id2name(env.mj_model, mujoco.mjtObj.mjOBJ_BODY, i), 
        env.mj_model.body_mass[i]
    ) 
    for i in range(env.mj_model.nbody)
]


[('world', np.float64(0.0)),
 ('link0', np.float64(0.629769)),
 ('link1', np.float64(4.970684)),
 ('link2', np.float64(0.646926)),
 ('link3', np.float64(3.228604)),
 ('link4', np.float64(3.587895)),
 ('link5', np.float64(1.225946)),
 ('link6', np.float64(1.666555)),
 ('link7', np.float64(0.735522)),
 ('hand', np.float64(0.73)),
 ('left_finger', np.float64(0.015)),
 ('right_finger', np.float64(0.015)),
 ('nut', np.float64(0.959904)),
 ('peg', np.float64(1.6917119999999999)),
 ('mocap_target', np.float64(1.387152))]

In [ ]:

init_state=  env.reset(jax.random.PRNGKey(0))
state=init_state



In [ ]:
from custom_envs import mjx_env


state.data
mjx_env.get_sensor_data(
        env.mj_model, state.data, "torso_subtreelinvel"
    )


KeyError: "Invalid name 'torso_subtreelinvel'. Valid names: ['hand_capsule_floor_found', 'left_finger_pad_floor_found', 'nut_handle_hand_found', 'right_finger_pad_floor_found']"

: 

In [ ]:
state = env.step(state, jnp.ones(env.action_size))
state.data.xpos



In [ ]:
from learning.module.wrapper.evaluator import AdvEvaluator


evaluator = AdvEvaluator(
        env,
        lambda x : x,
        num_eval_envs=128,
        episode_length=1000,
        action_repeat=2,
        key=jax.random.PRNGKey(0),
    )
dynamics_params = jnp.zeros((128,14))
metrics = evaluator.run_evaluation(dynamics_params, dynamics_params, {})
